# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-19 08:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='all_authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='all_poems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('poem', models.TextField(max_length=300000)),
                ('show_poem', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('poet', models.ManyToManyField(to='core.all_authors')),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
                'verbose_name': 'Poem',
                'verbose_name_plural': 'Poems',
            },
        ),
        migrations.CreateModel(
            name='all_riddles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('riddle', models.TextField(max_length=30000)),
                ('answer', models.CharField(blank=True, max_length=500, null=True)),
                ('explanation', models.TextField(blank=True, max_length=30000, null=True)),
                ('show_riddle', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('riddler', models.ManyToManyField(to='core.all_authors')),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
                'verbose_name': 'Riddle',
                'verbose_name_plural': 'Riddles',
            },
        ),
        migrations.CreateModel(
            name='all_stories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('story', models.TextField(max_length=30000)),
                ('show_story', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ManyToManyField(to='core.all_authors')),
                ('related_story', models.ManyToManyField(blank=True, null=True, related_name='_all_stories_related_story_+', to='core.all_stories')),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
            },
        ),
        migrations.CreateModel(
            name='taggers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=20)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(max_length=1000)),
            ],
            options={
                'ordering': ['-tag_name'],
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AddField(
            model_name='all_stories',
            name='tags',
            field=models.ManyToManyField(to='core.taggers'),
        ),
        migrations.AddField(
            model_name='all_riddles',
            name='tags',
            field=models.ManyToManyField(to='core.taggers'),
        ),
        migrations.AddField(
            model_name='all_poems',
            name='tags',
            field=models.ManyToManyField(to='core.taggers'),
        ),
    ]
