# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-01 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about',
            new_name='all_about',
        ),
    ]
